#!/usr/bin/env bash

case "$(uname)" in
Darwin)
  eval "$(/opt/homebrew/bin/brew shellenv)"
  ;;
Linux)
  for BREW_PATH in "$HOME/homebrew/bin/brew" "$HOME/linuxbrew/.linuxbrew/bin/brew"; do
    [ -x "$BREW_PATH" ] && eval "$("$BREW_PATH" shellenv)"
  done
  ;;
esac

eval "$(mise activate zsh)"

[[ -f "$HOME/.config/zsh/profile.local" ]] && source "$HOME/.config/zsh/profile.local"
