# --- Powerlevel10k Instant Prompt ---
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# --- Oh My Zsh ---
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="powerlevel10k/powerlevel10k"

# --- Plugins Configuration ---
zstyle ':omz:plugins:eza' 'git-status' yes
zstyle ':omz:plugins:eza' 'header' yes
zstyle ':omz:plugins:eza' 'icons' yes
zstyle ':omz:plugins:eza' 'color-scale' all

zstyle ':omz:plugins:alias-finder' autoload yes
zstyle ':omz:plugins:alias-finder' exact yes

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#636DA6"
ZSH_AUTOSUGGEST_STRATEGY=completion

plugins=( aliases alias-finder azure colored-man-pages command-not-found docker docker-compose eza git helm jsontools kubectl pip python rails rake ruby z zsh-autopair zsh-autosuggestions zsh-history-substring-search zsh-syntax-highlighting zsh-vi-mode )

source $ZSH/oh-my-zsh.sh

# --- Editor Configuration ---
if command -v nvim >/dev/null 2>&1; then
  export EDITOR="nvim"
elif command -v nvim >/dev/null 2>&1; then
  export EDITOR="vim"
else
  export EDITOR="vi"
fi

# --- Aliases ---
alias vim="nvim"
e() {
  "$EDITOR" "$@"
}
if command -v batcat &> /dev/null; then
  alias cat="batcat"
fi
alias ll='ls -la --total-size'
alias la='ls -a'
alias lt='ls --tree'
alias g="lazygit"
alias y="yadm enter lazygit"

function x() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
		builtin cd -- "$cwd"
	fi
	rm -f -- "$tmp"
}

# --- Bindkeys ---
bindkey -v
bindkey '^x' clear-screen
bindkey '^h' vi-backward-char
bindkey '^l' vi-forward-char
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down

# --- Zsh Vi Mode Colors ---
ZVM_VI_HIGHLIGHT_FOREGROUND=#82AAFF
ZVM_VI_HIGHLIGHT_BACKGROUND=#636DA6

# --- Prompt ---
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# --- Source scripts --

scripts_dir="${0:A:h}/zshrc.os"

for script in "$scripts_dir"/*.sh; do
    if [[ -r "$script" ]]; then
        source "$script"
    fi
done
