# Font
font_family      CommitMono Nerd Font Mono
font_size        16.0
disable_ligatures always

# Colors (iTerm2 dark-mode colors, defined in Display P3)
macos_colorspace     displayp3
foreground           #f9f9f9
background           #000000
cursor               #ff966c
cursor_text_color    #000000
selection_background #2d3f76
selection_foreground none

color0  #000000
color1  #c53b53
color2  #3ba08e
color3  #ff966c
color4  #636da6
color5  #c099ff
color6  #65bcff
color7  #cccccc
color8  #767676
color9  #e26a75
color10 #c3e88d
color11 #ffc777
color12 #82aaff
color13 #fca7ea
color14 #4fd6be
color15 #ffffff

# Cursor
cursor_shape       beam
cursor_blink_interval 0

# Window
background_opacity 0.85
background_blur    7
macos_option_as_alt left
