#!/usr/bin/env bash

# Save this file as ~/.config/yadm/bootstrap and make it executable. It will
# execute all executable files (excluding templates and editor backups) in the
# ~/.config/yadm/bootstrap.d directory when run.

# Import colors
source "${HOME}/.config/yadm/scripts/colors.sh"

# Define common color templates
T_OK="${GREEN}${BOLD}"
T_WARNING="${YELLOW}${BOLD}"
T_ERROR="${RED}${BOLD}"
T_PATH="${CYAN}${UNDERLINE}"

set -eu

# Directory to look for bootstrap executables in
BOOTSTRAP_D="${BASH_SOURCE[0]}.d"

if [[ ! -d "${BOOTSTRAP_D}" ]]; then
  printf "[${T_ERROR}ERROR${NC}] bootstrap directory '${BOOTSTRAP_D}' not found" >&2
  exit 1
fi

declare -a bootstraps
while IFS= read -r bootstrap; do
  bootstraps+=("$bootstrap")
done < <(find -L "${BOOTSTRAP_D}" \( -type f -or -type l \) -not -name '*##*' -not -name '*~$*' | sort -n)

for bootstrap in "${bootstraps[@]}"; do
  if [[ -x "${bootstrap}" ]]; then
    printf "\nExecuting ${T_PATH}$(basename "${bootstrap}")${NC}\n"
    if ! "${bootstrap}"; then
      printf "[${T_ERROR}ERROR${NC}] bootstrap '$(basename "${bootstrap}")' failed\n" >&2
      exit 1
    fi
    printf "[${T_OK}SUCCEDED${NC}]\n"
  fi
done
