[mgr]
prepend_keymap = [
  #defaults
  { on = "j", run = "arrow 1", desc = "Down" },
  { on = "k", run = "arrow -1", desc = "Up" },
  { on = "Q", run = "quit", desc = "Quit the process" },
  { on = "q", run = "quit --no-cwd-file", desc = "quit the process without outputting cwd-file" },
  { on = "i", run = "spot", desc = "Spot hovered file" },
  { on = "e", run = "open", desc = "Open selected files" },
	{ on = "E", run = "open --interactive", desc = "Open selected files interactively" },
	{ on = "<Space>", run = "toggle", desc = "Toggle the current selection state" },
  #bookmarks
  { on = "m", run = "plugin bookmarks save", desc = "Save current position as a bookmark" },
  { on = "'", run = "plugin bookmarks jump", desc = "Jump to a bookmark" },
  { on = [ "b", "d" ], run = "plugin bookmarks delete", desc = "Delete a bookmark" },
  { on = [ "b", "D" ], run = "plugin bookmarks delete_all", desc = "Delete all bookmarks" },
  #chmod
  { on = [ "c", "m" ], run = "plugin chmod", desc = "Chmod on selected files" },
  #compress
  { on = [ "c", "a", "a" ], run = "plugin compress", desc = "Archive selected files" },
  { on = [ "c", "a", "p" ], run = "plugin compress -p", desc = "Archive selected files (password)" },
  { on = [ "c", "a", "h" ], run = "plugin compress -ph", desc = "Archive selected files (password+header)" },
  { on = [ "c", "a", "l" ], run = "plugin compress -l", desc = "Archive selected files (compression level)" },
  { on = [ "c", "a", "u" ], run = "plugin compress -phl", desc = "Archive selected files (password+header+level)" },
  { on = [ "c", "a", "7" ], run = "plugin compress 7z", desc = "Archive selected files to 7z" },
  #diff
  { on = "<c-d>", run = "shell --block -- nvim -d $@", desc = "Diff the selected files" },
  #eza-preview
  { on = [ "T" ], run = "plugin eza-preview",  desc = "Toggle tree/list dir preview" },
  { on = [ "+" ], run = "plugin eza-preview --args='--inc-level'", desc = "Increment tree level" },
  { on = [ "_" ], run = "plugin eza-preview --args='--dec-level'", desc = "Decrement tree level" },
  { on = [ "$" ], run = "plugin eza-preview --args='--toggle-follow-symlinks'", desc = "Toggle tree follow symlinks" },
  #git
  { on = [ "g", "a" ], run = "shell --block -- git add $@", desc = "Add to Git Repo" },
  { on = [ "g", "D" ], run = "shell --block -- git rm --cached $@", desc = "Remove from Git Repo" },
  #vcs-files
  { on = [ "g", "c" ], run = "plugin vcs-files", desc = "Show Git file changes" },
  #lazygit
  { on = [ "g", "l" ], run = "plugin lazygit", desc = "run lazygit" },
  #relative-motions
  { on = "1", run = "plugin relative-motions 1", desc = "Move in relative steps" },
  { on = "2", run = "plugin relative-motions 2", desc = "Move in relative steps" },
  { on = "3", run = "plugin relative-motions 3", desc = "Move in relative steps" },
  { on = "4", run = "plugin relative-motions 4", desc = "Move in relative steps" },
  { on = "5", run = "plugin relative-motions 5", desc = "Move in relative steps" },
  { on = "6", run = "plugin relative-motions 6", desc = "Move in relative steps" },
  { on = "7", run = "plugin relative-motions 7", desc = "Move in relative steps" },
  { on = "8", run = "plugin relative-motions 8", desc = "Move in relative steps" },
  { on = "9", run = "plugin relative-motions 9", desc = "Move in relative steps" },
  #restore
  { on = "u", run = "plugin restore", desc = "Restore last deleted files/folders" },
  #smart-enter
  { on = "l", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
  #smart-filter
  { on = "F", run = "plugin smart-filter", desc = "Smart filter" },
  #smart-paste
  { on = "p", run = "plugin smart-paste", desc = "Paste into the hovered directory or CWD" },
  #what-size
  { on   = [ "c", "s" ], run  = "plugin what-size", desc = "Calc size of selection or cwd" },
]
