return {
	"mason-org/mason.nvim",
	opts = {
		ensure_installed = {
			"ast-grep",
			"bash-language-server",
			"checkmake",
			"clang-format",
			"clangd",
			"debugpy",
			"delve",
			"docker-compose-language-service",
			"dockerfile-language-server",
			"gofumpt",
			"golangci-lint",
			"gopls",
			"helm-ls",
			"html-lsp",
			"java-debug-adapter",
			"jdtls",
			"just-lsp",
			"kube-linter",
			"lua-language-server",
			"marksman",
			"pgformatter",
			"php-debug-adapter",
			"phpactor",
			"postgrestools",
			"pyright",
			"rubocop",
			"ruff",
			"sqruff",
			"standardrb",
			"stylelint",
			"stylelint-lsp",
			"superhtml",
			"taplo",
			"tree-sitter-cli",
			"typescript-language-server",
			"vim-language-server",
			"vint",
			"yaml-language-server",
			"yamlfmt",
			"yamllint",
		},
		ui = {
			border = "rounded",
			height = 0.8,
		},
	},
}
