return {
	"roobert/search-replace.nvim",
	opts = {},
	keys = {
		{
			"<leader>ro",
			mode = "v",
			"<CMD>SearchReplaceSingleBufferVisualSelection<CR>",
			desc = "Replace [o]pen",
			silent = true,
		},
		{
			"<leader>rvo",
			mode = "v",
			"<CMD>SearchReplaceWithinVisualSelection<CR>",
			desc = "Replace [o]pen",
			silent = true,
		},
		{
			"<leader>rvw",
			mode = "v",
			"<CMD>SearchReplaceWithinVisualSelectionCWord<CR>",
			desc = "Replace [w]ord",
			silent = true,
		},
		{
			"<leader>rs",
			mode = "n",
			"<CMD>SearchReplaceSingleBufferSelections<CR>",
			desc = "Replace [s]election list",
			silent = true,
		},
		{
			"<leader>ro",
			mode = "n",
			"<CMD>SearchReplaceSingleBufferOpen<CR>",
			desc = "Replace [o]pen",
			silent = true,
		},
		{
			"<leader>rw",
			mode = "n",
			"<CMD>SearchReplaceSingleBufferCWord<CR>",
			desc = "Replace [w]ord",
			silent = true,
		},
		{
			"<leader>rW",
			mode = "n",
			"<CMD>SearchReplaceSingleBufferCWORD<CR>",
			desc = "Replace [W]ORD",
			silent = true,
		},
		{
			"<leader>re",
			mode = "n",
			"<CMD>SearchReplaceSingleBufferCExpr<CR>",
			desc = "Replace [e]xpr",
			silent = true,
		},
		{
			"<leader>rf",
			mode = "n",
			"<CMD>SearchReplaceSingleBufferCFile<CR>",
			desc = "Replace [f]ile",
			silent = true,
		},

		{
			"<leader>rbs",
			mode = "n",
			"<CMD>SearchReplaceMultiBufferSelections<CR>",
			desc = "Replace [s]election list",
			silent = true,
		},
		{
			"<leader>rbo",
			mode = "n",
			"<CMD>SearchReplaceMultiBufferOpen<CR>",
			desc = "Replace [o]pen",
			silent = true,
		},
		{
			"<leader>rbw",
			mode = "n",
			"<CMD>SearchReplaceMultiBufferCWord<CR>",
			desc = "Replace [w]ord",
			silent = true,
		},
		{
			"<leader>rbW",
			mode = "n",
			"<CMD>SearchReplaceMultiBufferCWORD<CR>",
			desc = "Replace [W]ORD",
			silent = true,
		},
		{
			"<leader>rbe",
			mode = "n",
			"<CMD>SearchReplaceMultiBufferCExpr<CR>",
			desc = "Replace [e]xpr",
			silent = true,
		},
		{
			"<leader>rbf",
			mode = "n",
			"<CMD>SearchReplaceMultiBufferCFile<CR>",
			desc = "Replace [f]ile",
			silent = true,
		},
	},
}
