return {
	"chrisgrieser/nvim-various-textobjs",
	opts = { keymaps = { useDefaults = false } },
	keys = {
		{
			"im",
			"<cmd>lua require('various-textobjs').chainMember('inner')<cr>",
			mode = { "o", "x" },
			desc = "chain member",
		},
		{
			"am",
			"<cmd>lua require('various-textobjs').chainMember('outer')<cr>",
			mode = { "o", "x" },
			desc = "chain member",
		},
		{ "!", "<cmd>lua require('various-textobjs').diagnostic()<cr>", mode = { "o", "x" }, desc = "diagnostic" },
		{
			"gG",
			"<cmd>lua require('various-textobjs').entireBuffer()<cr>",
			mode = { "o", "x" },
			desc = "entire buffer",
		},
		{ "ik", "<cmd>lua require('various-textobjs').key('inner')<cr>", mode = { "o", "x" }, desc = "key" },
		{ "ak", "<cmd>lua require('various-textobjs').key('outer')<cr>", mode = { "o", "x" }, desc = "key" },
		{
			"i_",
			"<cmd>lua require('various-textobjs').lineCharacterwise('inner')<cr>",
			mode = { "o", "x" },
			desc = "line (charwise)",
		},
		{
			"a_",
			"<cmd>lua require('various-textobjs').lineCharacterwise('outer')<cr>",
			mode = { "o", "x" },
			desc = "line (charwise)",
		},
		{ "id", "<cmd>lua require('various-textobjs').number('inner')<cr>", mode = { "o", "x" }, desc = "number" },
		{ "ad", "<cmd>lua require('various-textobjs').number('outer')<cr>", mode = { "o", "x" }, desc = "number" },
		{ "iv", "<cmd>lua require('various-textobjs').value('inner')<cr>", mode = { "o", "x" }, desc = "value" },
		{ "av", "<cmd>lua require('various-textobjs').value('outer')<cr>", mode = { "o", "x" }, desc = "value" },
		{ "ie", "<cmd>lua require('various-textobjs').subword('inner')<cr>", mode = { "o", "x" }, desc = "subword" },
		{ "ae", "<cmd>lua require('various-textobjs').subword('outer')<cr>", mode = { "o", "x" }, desc = "subword" },
		{ "iL", "<cmd>lua require('various-textobjs').url()<cr>", mode = { "o", "x" }, desc = "url" },
	},
}
