return {
	"folke/which-key.nvim",
	opts = {
		spec = {
			{
				mode = { "n", "v" },
				{ "<leader>a", group = "annotations", icon = { icon = "󰆉 ", color = "cyan" } },
				{ "<leader>cc", group = "calc", icon = { icon = " ", color = "cyan" } },
				{ "<leader>cC", name = "Color Picker", icon = { icon = " ", color = "orange" } },
				{ "<leader>cP", name = "Pwned?", icon = { icon = " ", color = "red" } },
				{ "<leader>d", group = "diff", icon = { icon = " ", color = "yellow" } },
				{ "<leader>di", name = "Index", icon = { icon = " ", color = "blue" } },
				{ "<leader>dh", name = "History", icon = { icon = " ", color = "green" } },
				{ "<leader>dq", name = "Close Diffview", icon = { icon = "󰈆 ", color = "red" } },
				{ "<leader>gg", name = "Neogit", icon = { icon = "󰊢 ", color = "orange" } },
				{ "<leader>h", group = "history", icon = { icon = " ", color = "green" } },
				{ "<leader>n", group = "notes", icon = { icon = "󰠮 ", color = "blue" } },
				{ "<leader>o", group = "overseer", icon = { icon = " ", color = "red" } },
				{ "<leader>ob", name = "Task Builder", icon = { icon = "󰘙 ", color = "cyan" } },
				{ "<leader>oc", name = "Clear Cache", icon = { icon = "󰆴 ", color = "red" } },
				{ "<leader>oi", name = "Overseer Info", icon = { icon = " ", color = "blue" } },
				{ "<leader>ol", name = "Load Bundle", icon = { icon = " ", color = "green" } },
				{ "<leader>oq", name = "QuickAction Recent Task", icon = { icon = "󰑓 ", color = "red" } },
				{ "<leader>or", name = "Recent Tasks", icon = { icon = " ", color = "green" } },
				{ "<leader>ot", name = "Template Tasks", icon = { icon = "󰑮 ", color = "red" } },
				{ "<leader>ow", name = "Watch Tasks", icon = { icon = " ", color = "blue" } },
				{ "<leader>t", group = "terminal", icon = { icon = " ", color = "red" } },
				{ "<leader>tf", icon = { icon = " ", color = "red" } },
				{ "<leader>tt", icon = { icon = " ", color = "red" } },
				{ "<leader>tT", icon = { icon = " ", color = "red" } },
				{ "<leader>T", group = "test", icon = { icon = "󰱑", color = "red" } },
				{ "<leader>uc", group = "conceal", icon = { icon = "", color = "red" } },
				{ "<leader>uD", group = "dimming", icon = { icon = "", color = "blue" } },
				{ "<leader>x", group = "explorer", icon = { icon = "󰙅 ", color = "yellow" } },
				{ "<leader>xf", name = "Root Dir (floating)", icon = { icon = " ", color = "blue" } },
				{ "<leader>xF", name = "CWD (floating)", icon = { icon = " ", color = "blue" } },
				{ "<leader>xx", name = "Root Dir", icon = { icon = "󰙅 ", color = "yellow" } },
				{ "<leader>xX", name = "CWD", icon = { icon = "󰙅 ", color = "yellow" } },
				{ "<leader>Q", group = "quickfix", icon = { icon = "󱖫 ", color = "green" } },
				{ "<leader>.", group = "Other", icon = { icon = "󰇘 ", color = "blue" } },
				{ "<a-d>", group = "debug", icon = { icon = "󰃤 ", color = "red" } },
				{ "gs", group = "surround", icon = { icon = "󰅲 ", color = "yellow" } },
			},
			{
				mode = { "x" },
				{ "<leader>cs", name = "CodeSnap", icon = { icon = " ", color = "orange" } },
				{ "<leader>csa", icon = { icon = " ", color = "orange" } },
				{ "<leader>csc", icon = { icon = " ", color = "orange" } },
				{ "<leader>css", icon = { icon = " ", color = "orange" } },
				{ "<leader>csv", name = "With Highlight", icon = { icon = " ", color = "cyan" } },
				{ "<leader>csvc", icon = { icon = " ", color = "orange" } },
				{ "<leader>csvs", icon = { icon = " ", color = "orange" } },
			},
		},
		plugins = {
			registers = true,
		},
	},
}
