return {
	"folke/which-key.nvim",
	opts = {
		spec = {
			{
				mode = { "n", "v" },
				{ "<leader>a", group = "annotations", icon = { icon = "󰆉 ", color = "cyan" } },
				{ "<leader>cc", group = "calc", icon = { icon = " ", color = "cyan" } },
				{ "<leader>cC", desc = "Color Picker", icon = { icon = " ", color = "orange" } },
				{ "<leader>cP", desc = "Pwned?", icon = { icon = " ", color = "red" } },
				{ "<leader>d", group = "diff", icon = { icon = " ", color = "yellow" } },
				{ "<leader>di", desc = "Index", icon = { icon = " ", color = "blue" } },
				{ "<leader>dh", desc = "History", icon = { icon = " ", color = "green" } },
				{ "<leader>dq", desc = "Close Diffview", icon = { icon = "󰈆 ", color = "red" } },
				{ "<leader>gg", desc = "Neogit", icon = { icon = "󰊢 ", color = "orange" } },
				{ "<leader>h", group = "history", icon = { icon = " ", color = "green" } },
				{ "<leader>n", group = "notes", icon = { icon = "󰠮 ", color = "blue" } },
				{ "<leader>o", group = "overseer", icon = { icon = " ", color = "red" } },
				{ "<leader>ob", desc = "Task Builder", icon = { icon = "󰘙 ", color = "cyan" } },
				{ "<leader>oc", desc = "Clear Cache", icon = { icon = "󰆴 ", color = "red" } },
				{ "<leader>oi", desc = "Overseer Info", icon = { icon = " ", color = "blue" } },
				{ "<leader>ol", desc = "Load Bundle", icon = { icon = " ", color = "green" } },
				{ "<leader>oq", desc = "QuickAction Recent Task", icon = { icon = "󰑓 ", color = "red" } },
				{ "<leader>or", desc = "Recent Tasks", icon = { icon = " ", color = "green" } },
				{ "<leader>ot", desc = "Template Tasks", icon = { icon = "󰑮 ", color = "red" } },
				{ "<leader>ow", desc = "Watch Tasks", icon = { icon = " ", color = "blue" } },
				{ "<leader>t", group = "terminal", icon = { icon = " ", color = "red" } },
				{ "<leader>tf", icon = { icon = " ", color = "red" } },
				{ "<leader>tt", icon = { icon = " ", color = "red" } },
				{ "<leader>tT", icon = { icon = " ", color = "red" } },
				{ "<leader>uc", group = "conceal", icon = { icon = "", color = "red" } },
				{ "<leader>uD", group = "dimming", icon = { icon = "", color = "blue" } },
				{ "<leader>x", group = "explorer", icon = { icon = "󰙅 ", color = "yellow" } },
				{ "<leader>xf", desc = "Root Dir (floating)", icon = { icon = " ", color = "blue" } },
				{ "<leader>xF", desc = "CWD (floating)", icon = { icon = " ", color = "blue" } },
				{ "<leader>xx", desc = "Root Dir", icon = { icon = "󰙅 ", color = "yellow" } },
				{ "<leader>xX", desc = "CWD", icon = { icon = "󰙅 ", color = "yellow" } },
				{ "<leader>Q", group = "quickfix", icon = { icon = "󱖫 ", color = "green" } },
				{ "<leader>.", group = "Other", icon = { icon = "󰇘 ", color = "blue" } },
				{ "<a-d>", group = "debug", icon = { icon = "󰃤 ", color = "red" } },
				{ "gs", group = "surround", icon = { icon = "󰅲 ", color = "yellow" } },
			},
			{
				mode = { "x" },
				{ "<leader>cs", desc = "CodeSnap", icon = { icon = " ", color = "orange" } },
				{ "<leader>csa", icon = { icon = " ", color = "orange" } },
				{ "<leader>csc", icon = { icon = " ", color = "orange" } },
				{ "<leader>css", icon = { icon = " ", color = "orange" } },
				{ "<leader>csv", desc = "With Highlight", icon = { icon = " ", color = "cyan" } },
				{ "<leader>csvc", icon = { icon = " ", color = "orange" } },
				{ "<leader>csvs", icon = { icon = " ", color = "orange" } },
			},
		},
		plugins = {
			registers = true,
		},
	},
}
